import Foundation

/// Pasteboard markers (nspasteboard.org convention) that mean "do not record this".
/// Password managers and secure fields set these; we never capture them.
enum ConcealedPasteboardType {
    static let all: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]
}

/// Outcome of the capture-time privacy guard.
enum CaptureDecision: Equatable {
    case capture
    case skipConcealed
    case skipExcludedApp(String)
}

/// Outcome for legacy file-list pasteboard data. These entries can cause the
/// watcher to read local files, so they require stricter provenance and path checks.
enum FileListCaptureDecision: Equatable {
    case capture([String])
    case skipEmpty
    case skipUntrustedSource(String?)
    case skipInvalidPaths
}

/// Pure capture-time privacy guard: decides whether a pasteboard change may enter history.
/// Holds no I/O so it is exhaustively testable; the watcher supplies live pasteboard/app state.
struct CapturePolicy {
    static let finderBundleID = "com.apple.finder"
    static let maxFileListEntries = 512
    static let maxFilePathLength = 4_096

    let excludedBundleIDs: Set<String>

    func decide(frontmostBundleID: String?, pasteboardTypes: [String]) -> CaptureDecision {
        if pasteboardTypes.contains(where: ConcealedPasteboardType.all.contains) {
            return .skipConcealed
        }
        if let bundleID = frontmostBundleID, excludedBundleIDs.contains(bundleID) {
            return .skipExcludedApp(bundleID)
        }
        return .capture
    }

    /// Content-length filter: a copied string must clear the user's minimum length to be captured.
    /// `minLength <= 0` disables it; whitespace-only content never clears a positive threshold.
    /// Static + pure so the watcher's min-length gate is testable in `YankCore`.
    static func meetsMinimumLength(_ text: String, minLength: Int) -> Bool {
        guard minLength > 0 else { return true }
        return text.trimmingCharacters(in: .whitespacesAndNewlines).count >= minLength
    }

    /// Legacy file-list pasteboards are only trusted from Finder. AppKit does not expose an
    /// authenticated pasteboard writer, so the frontmost app is a best-effort safety hint rather
    /// than a provenance guarantee.
    func decideFileListCapture(frontmostBundleID: String?, filePaths: [String]) -> FileListCaptureDecision {
        guard !filePaths.isEmpty else { return .skipEmpty }
        guard frontmostBundleID == Self.finderBundleID else {
            return .skipUntrustedSource(frontmostBundleID)
        }
        guard filePaths.count <= Self.maxFileListEntries,
              let normalizedPaths = Self.normalizedLocalFilePaths(filePaths) else {
            return .skipInvalidPaths
        }
        return .capture(normalizedPaths)
    }

    private static func normalizedLocalFilePaths(_ rawPaths: [String]) -> [String]? {
        var normalizedPaths: [String] = []
        normalizedPaths.reserveCapacity(rawPaths.count)

        for rawPath in rawPaths {
            guard let normalizedPath = normalizedLocalFilePath(rawPath) else { return nil }
            normalizedPaths.append(normalizedPath)
        }

        return normalizedPaths
    }

    private static func normalizedLocalFilePath(_ rawPath: String) -> String? {
        let trimmedPath = rawPath.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedPath.isEmpty,
              trimmedPath.utf8.count <= maxFilePathLength,
              !trimmedPath.contains("\0") else {
            return nil
        }

        let fileURL: URL
        if let url = URL(string: trimmedPath), let scheme = url.scheme {
            guard scheme == "file", url.isFileURL else { return nil }
            fileURL = url
        } else {
            guard trimmedPath.hasPrefix("/") else { return nil }
            fileURL = URL(fileURLWithPath: trimmedPath)
        }

        guard !hasDotTraversalComponent(fileURL.path) else { return nil }
        let standardizedPath = fileURL.standardizedFileURL.path
        guard standardizedPath.hasPrefix("/") else { return nil }
        return standardizedPath
    }

    private static func hasDotTraversalComponent(_ path: String) -> Bool {
        path.split(separator: "/", omittingEmptySubsequences: false).contains { component in
            component == "." || component == ".."
        }
    }
}
