import Foundation
import Testing
@testable import YankCore

@Suite struct CapturePolicyTests {
    @Test func plainTextIsCaptured() {
        let policy = CapturePolicy(excludedBundleIDs: [])
        #expect(
            policy.decide(frontmostBundleID: "com.app.editor", pasteboardTypes: ["public.utf8-plain-text"]) ==
            .capture
        )
    }

    @Test func concealedMarkersAreSkipped() {
        let policy = CapturePolicy(excludedBundleIDs: [])
        #expect(policy.decide(frontmostBundleID: "x", pasteboardTypes: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]) == .skipConcealed)
        #expect(policy.decide(frontmostBundleID: nil, pasteboardTypes: ["org.nspasteboard.TransientType"]) == .skipConcealed)
        #expect(policy.decide(frontmostBundleID: nil, pasteboardTypes: ["org.nspasteboard.AutoGeneratedType"]) == .skipConcealed)
    }

    @Test func excludedAppIsSkipped() {
        let policy = CapturePolicy(excludedBundleIDs: ["com.bitwarden.desktop"])
        #expect(policy.decide(frontmostBundleID: "com.bitwarden.desktop", pasteboardTypes: ["t"]) == .skipExcludedApp("com.bitwarden.desktop"))
        #expect(policy.decide(frontmostBundleID: "com.app.editor", pasteboardTypes: ["t"]) == .capture)
        #expect(policy.decide(frontmostBundleID: nil, pasteboardTypes: ["t"]) == .capture)
    }

    @Test func concealedTakesPrecedenceOverExclusion() {
        let policy = CapturePolicy(excludedBundleIDs: ["com.bitwarden.desktop"])
        #expect(
            policy.decide(frontmostBundleID: "com.bitwarden.desktop", pasteboardTypes: ["org.nspasteboard.ConcealedType"]) ==
            .skipConcealed
        )
    }

    @Test func finderFileListsAreCapturedAsNormalizedLocalPaths() {
        let policy = CapturePolicy(excludedBundleIDs: [])

        #expect(
            policy.decideFileListCapture(
                frontmostBundleID: CapturePolicy.finderBundleID,
                filePaths: ["/Users/alex/Desktop/image.png", "file:///Users/alex/Desktop/second.jpg"]
            ) ==
            .capture(["/Users/alex/Desktop/image.png", "/Users/alex/Desktop/second.jpg"])
        )
    }

    @Test func fileListsFromNonFinderAppsAreSkipped() {
        let policy = CapturePolicy(excludedBundleIDs: [])

        #expect(
            policy.decideFileListCapture(
                frontmostBundleID: "com.attacker.copyhelper",
                filePaths: ["/Users/alex/Pictures/private.png"]
            ) ==
            .skipUntrustedSource("com.attacker.copyhelper")
        )
        #expect(
            policy.decideFileListCapture(
                frontmostBundleID: nil,
                filePaths: ["/Users/alex/Pictures/private.png"]
            ) ==
            .skipUntrustedSource(nil)
        )
    }

    @Test func fileListsRejectInvalidOrNonLocalPaths() {
        let policy = CapturePolicy(excludedBundleIDs: [])

        let invalidFileLists = [
            ["relative/image.png"],
            ["~/Pictures/image.png"],
            ["https://example.com/image.png"],
            ["smb://server/share/image.png"],
            ["/Users/alex/Pictures/../Secrets/image.png"],
            ["/Users/alex/Pictures/\u{0}image.png"]
        ]

        for filePaths in invalidFileLists {
            #expect(
                policy.decideFileListCapture(
                    frontmostBundleID: CapturePolicy.finderBundleID,
                    filePaths: filePaths
                ) ==
                .skipInvalidPaths
            )
        }
    }

    @Test func fileListsRejectEntryFloods() {
        let policy = CapturePolicy(excludedBundleIDs: [])
        let filePaths = Array(repeating: "/Users/alex/Desktop/image.png", count: CapturePolicy.maxFileListEntries + 1)

        #expect(
            policy.decideFileListCapture(
                frontmostBundleID: CapturePolicy.finderBundleID,
                filePaths: filePaths
            ) ==
            .skipInvalidPaths
        )
    }

    // MARK: - Minimum-length filter

    @Test func minimumLengthDisabledCapturesEverything() {
        #expect(CapturePolicy.meetsMinimumLength("", minLength: 0))
        #expect(CapturePolicy.meetsMinimumLength("a", minLength: 0))
        #expect(CapturePolicy.meetsMinimumLength("  ", minLength: -5))
    }

    @Test func minimumLengthFiltersShortAndWhitespaceOnlyContent() {
        #expect(!CapturePolicy.meetsMinimumLength("hi", minLength: 5))
        // Whitespace is trimmed before measuring, so blank content never clears a positive bar.
        #expect(!CapturePolicy.meetsMinimumLength("   \n\t ", minLength: 1))
    }

    @Test func minimumLengthAcceptsContentAtOrAboveThreshold() {
        #expect(CapturePolicy.meetsMinimumLength("hello", minLength: 5))
        #expect(CapturePolicy.meetsMinimumLength("hello world", minLength: 5))
        // Leading/trailing whitespace doesn't count toward the threshold.
        #expect(CapturePolicy.meetsMinimumLength("  hello  ", minLength: 5))
    }
}
